# Generated by Django 6.0.6 on 2026-07-23 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('postcode', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='استان')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_purchase', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت در لحظه خرید')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
